### ISSUE TITLE
bug in submission

### ISSUE THREAD

**Issue by Mikkeljeppesen1** [praxisdigital/assignsubmission_pxaiwriter#12]
Found on finansudd only: https://moodle.finansudd.dk/course/view.php?id=967&sectionid=7405

Ive created a default ai-writer assignment, but when i try to use ai writer as a student the input dosent appear. See this example 

![Image](https://github.com/praxisdigital/assignsubmission_pxaiwriter/assets/42199572/70b62d52-b56e-45bd-ad54-e532672c4d5a)

I can see in the html the box is displyed none

I get this error in the console:

![Image](https://github.com/praxisdigital/assignsubmission_pxaiwriter/assets/42199572/9d3aa51c-2e9f-4e90-b61d-439e248ba4fb)

**Comment by sampraxis** [comment]
@Mikkeljeppesen1 
I couldn't reproduce the issue.

**Comment by Mikkeljeppesen1** [comment]
@sampraxis i will try again and if dont either we will close the case

**Comment by Mikkeljeppesen1** [comment]
case closed - cant reproduce it
