### ISSUE TITLE
Bug report on AI Writer from a client

### ISSUE THREAD

**Issue by superfoght** [praxisdigital/assignsubmission_pxaiwriter#13]
We have to discuss wether this plugin is really up to par in terms of the output it generates, when showing the changes between the steps. I know Sam has said that this below is due to how the engine handles it. But if it can't be of better quality than this, then frankly I think we should scrap this.

Let's discuss this after the summer holidays when Tue is back as well..

Feedback from the client. 

Jeg har lavet et par test og leget med indstillingerne, men ak. Det virker noget upålideligt. Så jeg ikke rigtigt tør rulle det ud til underviserne. Har jeres andre kunder nogle gode erfaringer?
Af fejl som opstår på trods af indstillinger er:
Som tidligere omtalt sære rettelser og helt nye ord.
Og ved Expand Selection, kommer der slet ingen markering/farvning.

![Image](https://github.com/praxisdigital/assignsubmission_pxaiwriter/assets/2778015/93d72f1d-cf8c-4965-84b8-04e6fb2e7bf8)

![Image](https://github.com/praxisdigital/assignsubmission_pxaiwriter/assets/2778015/d4093f6c-aece-4e0f-846e-9dd5a616b8d1)

**Comment by sampraxis** [comment]
We need more example for this.

**Comment by TubsDK** [comment]
Should we switch to? https://github.com/caxy/php-htmldiff

**Comment by mcardle** [comment]
@sampraxis maybe you could have a look at this.

**Comment by sampraxis** [comment]
@superfoght 
Ready for testing.

Just use **smo_GH-17_42** branch for testing.
The branch is also contain the changes from #17 issue
