### ISSUE TITLE
Field not marked correct

### ISSUE THREAD

**Issue by Mikkeljeppesen1** [praxisdigital/assignsubmission_pxaiwriter#18]
Found on finansudd - newest plugin version

Adding a new assignment and scroll down, i see the ai writer is not default marked in the settings, but aiwriter-input shown. Seems strange to me. 

![image](https://github.com/praxisdigital/assignsubmission_pxaiwriter/assets/42199572/45f7bf4b-a20f-4e2a-9ac4-295a26ccda3e)

**Comment by sampraxis** [comment]
@Mikkeljeppesen1 

Maybe the setting in site administration wasn't enabled by default.
https://moodle.finansudd.dk/admin/settings.php?section=assignsubmission_pxaiwriter

**Comment by Mikkeljeppesen1** [comment]
yeah, its gone now, so lets just close this one :)
