### ISSUE TITLE
Create a validation check

### ISSUE THREAD

**Issue by TubsDK** [praxisdigital/assignsubmission_pxaiwriter#2]
Currently an assignment must have a due date for the AI Writer to work, but this is not validated. 

It should not be possible to save an AI Writer assignment, where due date is not set.

**Comment by sampraxis** [comment]
Pull request #5 is being review by @Snowdle

**Comment by sampraxis** [comment]
Test bundle:
#1 
#2
#3 

Branch: [smo_GH-dev_master](https://github.com/praxisdigital/assignsubmission_pxaiwriter/tree/smo_GH-dev_master)
Test by follow the description of the issues ( #1, #2, #3 )

**Comment by superfoght** [comment]
@sampraxis @mcardle 

I tried to upgrade on Moodlefour test site and get the following error: 



![Image](https://user-images.githubusercontent.com/2778015/231095509-901613a0-098c-4cf9-a868-593f825d5e05.png)

**Comment by sampraxis** [comment]
@superfoght 
It's ready to be test again.

**Comment by sampraxis** [comment]
@superfoght had tested it. (Passed)

**Comment by sampraxis** [comment]
This should be close together with #1 when it has passed the test.
