### ISSUE TITLE
Error while trying to delete course

### ISSUE THREAD

**Issue by Mikkeljeppesen1** [praxisdigital/assignsubmission_pxaiwriter#23]
Found on moodlefour when trying to dele a course eith adhoc tasks 

Execute adhoc task: core_course\task\course_delete_modules
Adhoc task id: 4176
Adhoc task custom data: {"cms":[{"id":"4599","course":"164","module":"1","instance":"636","section":"1601","idnumber":"","added":"1695711536","score":"0","indent":"0","visible":"1","visibleoncoursepage":"1","visibleold":"1","groupmode":"0","groupingid":"0","completion":"2","completiongradeitemnumber":null,"completionview":"1","completionexpected":"0","completionpassgrade":"0","showdescription":"0","availability":null,"deletioninprogress":"1","downloadcontent":"1","lang":""}],"userid":"2","realuserid":"2"}
... started 09:36:41. Current memory use 3.5 MB.
Debugging increased temporarily due to faildelay of 86400
... used 184 dbqueries
... used 2.6804459095001 seconds
Adhoc task failed: core_course\task\course_delete_modules,Kodefejl opdaget, den skal rettes af en programmør: The course module 4599 could not be deleted. FEJL: Mangler parameteret "assignment_id" i forespørgslen: /var/www/html/moodle/lib/dml/moodle_database.php(975) #0 /var/www/html/moodle/lib/dml/mysqli_native_moodle_database.php(1788): moodle_database->fix_sql_params('DELETE FROM mdl...', Array)
#1 /var/www/html/moodle/mod/assign/submission/pxaiwriter/classes/app/submission/repository.php(277): mysqli_native_moodle_database->delete_records_select('assignsubmissio...', 'WHERE assignmen...', Array)
#2 /var/www/html/moodle/mod/assign/submission/pxaiwriter/locallib.php(256): assignsubmission_pxaiwriter\app\submission\repository->delete_by_assignment_id(636)
#3 /var/www/html/moodle/mod/assign/locallib.php(841): assign_submission_pxaiwriter->delete_instance()
#4 /var/www/html/moodle/mod/assign/lib.php(58): assign->delete_instance()
#5 /var/www/html/moodle/course/lib.php(900): assign_delete_instance('636')
#6 /var/www/html/moodle/course/classes/task/course_delete_modules.php(66): course_delete_module('4599')
#7 /var/www/html/moodle/lib/classes/cron.php(508): core_course\task\course_delete_modules->execute()
#8 /var/www/html/moodle/lib/classes/cron.php(348): core\cron::run_inner_adhoc_task(Object(core_course\task\course_delete_modules))
#9 /var/www/html/moodle/lib/classes/cron.php(368): core\cron::run_adhoc_task(4176)
#10 /var/www/html/moodle/admin/cli/adhoc_task.php(154): core\cron::run_failed_adhoc_tasks('\\core_course\\ta...')
#11 {main}
Backtrace:
* line 508 of /lib/classes/cron.php: call to core_course\task\course_delete_modules->execute()
* line 348 of /lib/classes/cron.php: call to core\cron::run_inner_adhoc_task()
* line 368 of /lib/classes/cron.php: call to core\cron::run_adhoc_task()
* line 154 of /admin/cli/adhoc_task.php: call to core\cron::run_failed_adhoc_tasks()

Execute adhoc task: core_course\task\course_delete_modules
Adhoc task id: 4209
Adhoc task custom data: {"cms":[{"id":"4601","course":"125","module":"1","instance":"638","section":"1195","idnumber":"","added":"1695713485","score":"0","indent":"0","visible":"1","visibleoncoursepage":"1","visibleold":"1","groupmode":"0","groupingid":"0","completion":"1","completiongradeitemnumber":null,"completionview":"0","completionexpected":"0","completionpassgrade":"0","showdescription":"0","availability":null,"deletioninprogress":"1","downloadcontent":"1","lang":""}],"userid":"2","realuserid":"2"}
... started 09:36:44. Current memory use 12.1 MB.
Debugging increased temporarily due to faildelay of 86400

**Comment by Anders-Oerbaek-Pedersen** [comment]
@Mikkeljeppesen1 The issue seems to be moodlefour is running assignsubmission_pxaiwriter version 1.3.1 (Build: 2023-09-15) but this issue has been fixed in current version 1.3.2 (Build: 2023-10-06)

I have updated the plugin version in morris Build361 for site moodlefour, it is currently available in the test environment.

**Comment by Mikkeljeppesen1** [comment]
Thx @Anders-Oerbaek-Pedersen. Its working now. No real issue here = straight to close
