### ISSUE TITLE
Update the plugin with the possiblity to use GPT-4 turbo model

### ISSUE THREAD

**Issue by Mikkeljeppesen1** [praxisdigital/assignsubmission_pxaiwriter#24]
Make it possible to use: GPT-4 turbo model

UMC added: Right now, you can't select it in the settings, and a new abstraction layer needs to be created for it to work.

**Comment by sampraxis** [comment]
Ready for testing

Test instructions:
1. Go to settings ``/admin/settings.php?section=assignsubmission_pxaiwriter``
2. Select Model to ``gpt-4-turbo-preview``
3. Create a course.
4. Enroll a user into the course as student.
5. Add an assignment.
    * Set due date.
    * Select AI writer submission.
    * Save the assignment.
6. Add a submission to the assignment.
7. Write some into the text area.
8. Press ``Do AI magic``
9. Expect assignment to generate an AI text from input text.
