### ISSUE TITLE
Loop untill stop message recieved

### ISSUE THREAD

**Issue by TubsDK** [praxisdigital/assignsubmission_pxaiwriter#26]
Currently we only perform a request once and OpenAI might only generate a partial response. 

This behavior is documentet in https://platform.openai.com/docs/api-reference/chat/object specficiallyh the finish_reason which needs to be "stop" . It it is eg Lenght we need to re-query the endpoint

**Comment by sampraxis** [comment]
@TubsDK Do you have an example of the prompt that cause this issue?

**Comment by sampraxis** [comment]
Ready for testing.
Branch: **smo_GH-26_master**

Test instructions:
1. Try to decrease the number of max_tokens in the setting. ``/admin/settings.php?section=assignsubmission_pxaiwriter``
2. Create a course.
3. Create an assignment in the course.
4. Add AI writer as submission.
5. Go to the assignment.
6. Try to prompt something that would give a long text (very large number of tokens).
7. See if the text or sentence doesn't cut off after run ``Do AI magic``.

**Comment by superfoght** [comment]
It looks like it works as it should :)
