### ISSUE TITLE
Make it look pretty

### ISSUE THREAD

**Issue by TubsDK** [praxisdigital/assignsubmission_pxaiwriter#3]
Create an overview of the number of steps in the AI writer . 

eg.

(1) - (2) - (3) - Finish

**Comment by sampraxis** [comment]
Test bundle:
#1 
#2
#3 

Branch: [smo_GH-dev_master](https://github.com/praxisdigital/assignsubmission_pxaiwriter/tree/smo_GH-dev_master)
Test by follow the description of the issues ( #1, #2, #3 )

**Comment by sampraxis** [comment]
@superfoght had tested it. (Passed)

**Comment by sampraxis** [comment]
This should be close together with #1 when it has passed the test.
