### ISSUE TITLE
Extra Prompt

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/assignsubmission_pxaiwriter#30]
assignsubmission_pxaiwriter estimate this from KVUC:

At KVUC, we've discussed adding a prompt field in Settings, where instructors can write a prompt that will be included in the students' prompts in Step 1, but will not be visible to the student.

It could by default be blank, so the plug-in would function as before.

I immediately think that it would be a simple, yet useful extension.

https://app-eu1.hubspot.com/contacts/25645903/record/0-5/3077155275

**Comment by TubsDK** [comment]
Reply with 1 day (moxis sponsors the rest of the development)

**Comment by neeesn** [comment]
The Client has accepted 1 day of programming.

**Comment by frederikmillingpytlick** [comment]
Ready for test @neeesn 

Will you make sure the customer is charged?

**Comment by neeesn** [comment]
When testing nothing happens when answering the assignment, its loading for a looong time and then this error:


![Image](https://github.com/user-attachments/assets/4232a274-5605-439b-b2c4-f35246c8fdf4)

https://kundeteam.moodle.moxis.dk/mod/assign/view.php?id=5265&action=editsubmission - on this course: https://kundeteam.moodle.moxis.dk/course/view.php?id=63

Assignement - med en Bøhmand

**Comment by frederikmillingpytlick** [comment]
Ready for testing again @neeesn

I've removed the "GPT-4 Turbo" model, and all sites which previously had it enabled will switch to the newly added model "GPT-4o Mini". I've also added the "GPT-4o" model

**Comment by neeesn** [comment]
@frederikmillingpytlick When i write something in the prompt in the assignement, The studnet cant answer the assignment. 
![image](https://github.com/user-attachments/assets/42cdf417-a902-488e-9710-4f37d84a2e60)

**Comment by frederikmillingpytlick** [comment]
@neeesn works perfectly fine for me?


![Image](https://github.com/user-attachments/assets/4791f33b-11dd-44e8-b79b-6dde4909c40e)

**Comment by neeesn** [comment]
@frederikmillingpytlick It doesnt work.

I created a new assignment and logged in with testelev1 / Test-elev1 and made a submission. it costet 0,15$ ok i think.
But then i logged in with testelev2 / Test-elev2 and made a different submission with it and it turned into a loop.  we got it stopped at cost 6,98$ and i thing it might have run longer if we hadnt stopped it. 

A thing i noticed when making my first text as studen is that it says its attempt 2 out of 2 ? 


![Image](https://github.com/user-attachments/assets/754de1bf-6f7a-4e3a-bddd-f49a9f9049c4)


Test elev2´s assignment:


![Image](https://github.com/user-attachments/assets/20ecfa66-0c28-4dc9-a883-dd9ecd22db32)


The upstart prompt is:


![Image](https://github.com/user-attachments/assets/c3a8b3f4-7fee-4455-90cc-528be26681b0)


Settings in plugin:


![Image](https://github.com/user-attachments/assets/4b9dcf70-14c1-496e-aeec-04a931b93cca)

**Comment by frederikmillingpytlick** [comment]
@neeesn Maybe fixed now? 🤞

**Comment by frederikmillingpytlick** [comment]
AI works now, but the "Do ai magic" button doesn't get disabled after using your last attempt. This should be added before testing with @neeesn again.

**Comment by frederikmillingpytlick** [comment]
Ready for testing again @neeesn

**Comment by neeesn** [comment]
After test the following has been noted: 

Set gpt-4o as standart and remove the 4.0 option in the list - its slower and more way more expensive 
Max tokens (assignsubmission_pxaiwriter | max_token) Set default to 5000 not the 216 it is now.

We need a description for the system prompt: 
![Image](https://github.com/user-attachments/assets/92ad9322-82f9-4761-822a-66e45adcd9e8)

when the changes are made make a test against https://platform.openai.com/playground/chat?models=gpt-4o to se the token generation in and out. - must not differ too much on same prompt.

**Comment by frederikmillingpytlick** [comment]
Awaiting https://github.com/praxisdigital/assignsubmission_pxaiwriter/issues/33

**Comment by frederikmillingpytlick** [comment]
Test with https://github.com/praxisdigital/assignsubmission_pxaiwriter/issues/33

**Comment by frederikmillingpytlick** [comment]
Tested with @TubsDK

**Comment by Mikkeljeppesen1** [comment]
@frederikmillingpytlick Scould this be removed to release?
