### ISSUE TITLE
Not all steps are recorded

### ISSUE THREAD

**Issue by TubsDK** [praxisdigital/assignsubmission_pxaiwriter#33]
**Describe the bug**
Sometimes not all steps are recorded

**To Reproduce**
Steps to reproduce the behavior. :
1. Go to https://master.praxis.dk/mod/assign/view.php?id=3620203
2. Add a prompt and press "Do ai magic 
3. Clear the text and enter a new prompt and Do AI magic
4. Finish the steps 
3. View the generated 

**Expected behavior**
Each press on "Do ai magic" should capture a substep eg 1.0 (text before ai generation ) , 1.1 (text after ai generation), 1.2 (updated text before ai generation), 1.3 (text after ai generation) 

**Current behavior**
only Step 2 is capturesd.

**Comment by TubsDK** [comment]
Note https://github.com/praxisdigital/assignsubmission_pxaiwriter/issues/30 also existes, so they should be fixed in same release.

**Comment by frederikmillingpytlick** [comment]
As far as I can see it works fine?

**Comment by TubsDK** [comment]
We clarified that all steps on "Tab 1" should be grouped as substeps til step 1.

**Comment by frederikmillingpytlick** [comment]
Test with https://github.com/praxisdigital/assignsubmission_pxaiwriter/issues/30

**Comment by frederikmillingpytlick** [comment]
Tested with @TubsDK

**Comment by Mikkeljeppesen1** [comment]
@frederikmillingpytlick and this to release as well?
